import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/header";

const sora = Sora({ subsets: ["latin"],
  weight: ['300', '400', '500']
 });

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className} suppressHydrationWarning={true}>
        {children}
        </body>
    </html>
  );
}
